"""Rewrite notebook code cells to load from precomputed cache files."""

import json

# ============================================================
# 1. LYAPUNOV NOTEBOOK
# ============================================================

with open('lyapunov_alpha_relationship.ipynb') as f:
    nb = json.load(f)

cells = nb['cells']
code_cells = [(i, c) for i, c in enumerate(cells) if c['cell_type'] == 'code']


def to_lines(text):
    return [l + '\n' for l in text.strip().split('\n')]


# Cell 0 (imports)
code_cells[0][1]['source'] = to_lines(
    "import sys\n"
    "sys.path.insert(0, '..')\n"
    "\n"
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "from scipy import integrate\n"
    "from petrification.maps import logistic\n"
    "from petrification.transforms import alpha_transform\n"
    "from petrification.iteration import iterate, iterate_transformed\n"
    "from petrification.bifurcation import compute_bifurcation, compute_bifurcation_transformed\n"
    "\n"
    "plt.rcParams.update({'figure.figsize': (12, 5), 'font.size': 12})\n"
    "\n"
    "# Load precomputed results\n"
    "_cache = np.load('cache/lyapunov_results.npz')"
)

# Cell 1 (lyapunov function def)
code_cells[1][1]['source'] = to_lines(
    "def lyapunov(f, a, x0, n_iter=10000, n_discard=1000, alpha=None):\n"
    "    if alpha is not None:\n"
    "        traj = iterate_transformed(logistic, alpha, a, x0, n_iter)\n"
    "    else:\n"
    "        traj = iterate(logistic, a, x0, n_iter)\n"
    "    traj = traj[n_discard:]\n"
    "    f_prime = a * (1 - 2 * traj[:-1])\n"
    "    if alpha is not None:\n"
    "        g_prime = 1 + alpha * (f_prime - 1)\n"
    "    else:\n"
    "        g_prime = f_prime\n"
    "    gp_abs = np.maximum(np.abs(g_prime), 1e-30)\n"
    "    return np.mean(np.log(gp_abs))"
)

# Cell 2 (§3: regular vs inverted scan)
code_cells[2][1]['source'] = to_lines(
    "# Load precomputed Lyapunov scans\n"
    "a_values = _cache['a_values']\n"
    "lyap_regular = _cache['lyap_regular']\n"
    "lyap_inverted = _cache['lyap_inverted']\n"
    "\n"
    "fig, axes = plt.subplots(3, 1, figsize=(14, 12))\n"
    "\n"
    "# Panel 1: Both Lyapunov exponents\n"
    "axes[0].plot(a_values, lyap_regular, 'b.', markersize=0.5, label='Regular (alpha=1)')\n"
    "axes[0].plot(a_values, lyap_inverted, 'r.', markersize=0.5, label='Inverted (alpha=-1)')\n"
    "axes[0].axhline(0, color='k', linewidth=0.5)\n"
    "axes[0].set(ylabel='Lambda', title='Lyapunov Exponents: Regular vs Inverted Logistic Map')\n"
    "axes[0].legend(markerscale=10)\n"
    "\n"
    "# Panel 2: Difference\n"
    "lyap_diff = lyap_inverted - lyap_regular\n"
    "axes[1].plot(a_values, lyap_diff, 'g.', markersize=0.5)\n"
    "axes[1].axhline(0, color='k', linewidth=0.5)\n"
    "axes[1].set(ylabel='Lambda_inv - Lambda_reg', title='Difference')\n"
    "\n"
    "# Panel 3: Correlation scatter\n"
    "mask = np.isfinite(lyap_regular) & np.isfinite(lyap_inverted)\n"
    "axes[2].scatter(lyap_regular[mask], lyap_inverted[mask], s=1, alpha=0.5)\n"
    "lims = [min(lyap_regular[mask].min(), lyap_inverted[mask].min()),\n"
    "        max(lyap_regular[mask].max(), lyap_inverted[mask].max())]\n"
    "axes[2].plot(lims, lims, 'r--', alpha=0.5, label='y = x (invariance)')\n"
    "axes[2].set(xlabel='Lambda_1 (regular)', ylabel='Lambda_inv (inverted)', title='Correlation')\n"
    "axes[2].set_aspect('equal')\n"
    "axes[2].legend()\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "\n"
    "# Statistics\n"
    "r = np.corrcoef(lyap_regular[mask], lyap_inverted[mask])[0, 1]\n"
    "rmse = np.sqrt(np.mean(lyap_diff[mask]**2))\n"
    "print(f'Pearson r = {r:.6f}')\n"
    "print(f'RMSE of difference = {rmse:.6f}')\n"
    "print(f'Max |difference| = {np.max(np.abs(lyap_diff[mask])):.6f}')"
)

# Cell 3 (§4: alpha sweep)
code_cells[3][1]['source'] = to_lines(
    "# Load precomputed alpha sweeps\n"
    "alpha_range = _cache['alpha_range']\n"
    "a_test = [3.2, 3.57, 3.83, 4.0]\n"
    "labels = ['a=3.2 (period-2)', 'a=3.57 (chaos onset)', 'a=3.83 (period-3)', 'a=4.0 (full chaos)']\n"
    "colors = ['blue', 'orange', 'green', 'red']\n"
    "sweep_keys = ['lyap_sweep_3_2', 'lyap_sweep_3_57', 'lyap_sweep_3_83', 'lyap_sweep_4_0']\n"
    "\n"
    "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n"
    "axes = axes.flatten()\n"
    "\n"
    "for idx, (a, label, color, key) in enumerate(zip(a_test, labels, colors, sweep_keys)):\n"
    "    lyap_vs_alpha = _cache[key]\n"
    "\n"
    "    axes[idx].plot(alpha_range, lyap_vs_alpha, color=color, linewidth=1)\n"
    "    axes[idx].axhline(0, color='k', linewidth=0.5)\n"
    "    axes[idx].axvline(1, color='gray', linestyle='--', alpha=0.5, label='alpha=1')\n"
    "    axes[idx].axvline(-1, color='gray', linestyle=':', alpha=0.5, label='alpha=-1')\n"
    "    axes[idx].axvline(0, color='gray', linestyle='-.', alpha=0.3, label='alpha=0')\n"
    "\n"
    "    # Mark the regular Lyapunov exponent\n"
    "    lam_reg = lyapunov(logistic, a, 0.4)\n"
    "    axes[idx].axhline(lam_reg, color='red', linestyle='--', alpha=0.3, label=f'Lambda_1 = {lam_reg:.3f}')\n"
    "\n"
    "    axes[idx].set(xlabel='alpha', ylabel='Lambda_alpha', title=label)\n"
    "    axes[idx].legend(fontsize=8)\n"
    "    axes[idx].set_ylim(-5, 3)\n"
    "\n"
    "plt.suptitle('Lyapunov Exponent vs alpha', fontsize=14)\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

# Cell 4 (§5: phase diagram)
code_cells[4][1]['source'] = to_lines(
    "# Load precomputed phase diagram\n"
    "alpha_range_2d = _cache['alpha_range_2d']\n"
    "a_range_2d = _cache['a_range_2d']\n"
    "lyap_map = _cache['lyap_map']\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(14, 8))\n"
    "extent = [a_range_2d[0], a_range_2d[-1], alpha_range_2d[0], alpha_range_2d[-1]]\n"
    "im = ax.imshow(lyap_map, extent=extent, aspect='auto', origin='lower',\n"
    "               cmap='RdBu_r', vmin=-3, vmax=1.5)\n"
    "plt.colorbar(im, ax=ax, label='Lyapunov exponent')\n"
    "\n"
    "# Critical lines\n"
    "ax.axhline(1.0, color='white', linestyle='--', linewidth=1, label='alpha=1 (regular)')\n"
    "ax.axhline(-1.0, color='white', linestyle=':', linewidth=1, label='alpha=-1 (inverted)')\n"
    "ax.axhline(0.0, color='yellow', linestyle='-.', linewidth=1, label='alpha=0 (identity)')\n"
    "\n"
    "# Contour at Lambda = 0 (chaos boundary)\n"
    "lyap_filled = np.where(np.isnan(lyap_map), 10, lyap_map)\n"
    "ax.contour(a_range_2d, alpha_range_2d, lyap_filled, levels=[0], colors='black', linewidths=2)\n"
    "\n"
    "ax.set(xlabel='Parameter a', ylabel='alpha', title='(alpha, a) Lyapunov Phase Diagram')\n"
    "ax.legend(loc='upper left')\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

# Cell 5 (§6: theory vs computation)
code_cells[5][1]['source'] = to_lines(
    "# Theoretical prediction at a=4, arcsine measure\n"
    "def predicted_lyapunov_alpha(alpha, a=4.0):\n"
    "    def integrand(x):\n"
    "        fp = a * (1 - 2 * x)\n"
    "        gp = 1 + alpha * (fp - 1)\n"
    "        if abs(gp) < 1e-30:\n"
    "            return -60 / (np.pi * np.sqrt(x * (1 - x) + 1e-30))\n"
    "        return np.log(abs(gp)) / (np.pi * np.sqrt(x * (1 - x) + 1e-30))\n"
    "    result, _ = integrate.quad(integrand, 0.001, 0.999, limit=200)\n"
    "    return result\n"
    "\n"
    "# Known: Lambda_1 = ln(2) at a=4\n"
    "print(f'Known: Lambda_1 = ln(2) = {np.log(2):.6f}')\n"
    "print(f'Prediction: Lambda_1 = {predicted_lyapunov_alpha(1.0):.6f}')\n"
    "print()\n"
    "\n"
    "# Load precomputed orbit averages, compute theory predictions\n"
    "alpha_test = _cache['alpha_test_theory']\n"
    "lyap_computed = _cache['lyap_computed_theory']\n"
    "lyap_predicted = np.array([predicted_lyapunov_alpha(a) for a in alpha_test])\n"
    "\n"
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n"
    "\n"
    "ax1.plot(alpha_test, lyap_predicted, 'r-', linewidth=2, label='Predicted (arcsine integral)')\n"
    "ax1.plot(alpha_test, lyap_computed, 'b.', markersize=4, label='Computed (orbit average)')\n"
    "ax1.axhline(np.log(2), color='gray', linestyle='--', alpha=0.5, label='ln(2)')\n"
    "ax1.axhline(0, color='k', linewidth=0.5)\n"
    "ax1.axvline(1, color='gray', linestyle=':', alpha=0.3)\n"
    "ax1.set(xlabel='alpha', ylabel='Lambda_alpha', title='Lyapunov at a=4: Theory vs Computation')\n"
    "ax1.legend()\n"
    "\n"
    "# Residual\n"
    "mask = np.isfinite(lyap_computed)\n"
    "residual = lyap_computed - lyap_predicted\n"
    "ax2.plot(alpha_test[mask], residual[mask], 'g.', markersize=4)\n"
    "ax2.axhline(0, color='k', linewidth=0.5)\n"
    "ax2.set(xlabel='alpha', ylabel='Predicted - Computed', title='Prediction Error')\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "\n"
    "# Key question: is Lambda_alpha = Lambda_1 for all alpha?\n"
    "print(f'Lambda(alpha=1)   = {predicted_lyapunov_alpha(1.0):.6f}')\n"
    "print(f'Lambda(alpha=-1)  = {predicted_lyapunov_alpha(-1.0):.6f}')\n"
    "print(f'Lambda(alpha=0.5) = {predicted_lyapunov_alpha(0.5):.6f}')\n"
    "print(f'Lambda(alpha=2)   = {predicted_lyapunov_alpha(2.0):.6f}')\n"
    "print(f'Invariant? {abs(predicted_lyapunov_alpha(1.0) - predicted_lyapunov_alpha(-1.0)) < 0.01}')"
)

# Cell 6 (§7: period map)
code_cells[6][1]['source'] = to_lines(
    "# Load precomputed period map\n"
    "alpha_range_p = _cache['alpha_range_p']\n"
    "a_range_p = _cache['a_range_p']\n"
    "period_map = _cache['period_map']\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(14, 8))\n"
    "\n"
    "# log2 of period for coloring\n"
    "period_display = period_map.copy().astype(float)\n"
    "period_display[period_display <= 0] = 0  # chaotic/diverged\n"
    "mask_pos = period_display > 0\n"
    "period_display[mask_pos] = np.log2(np.maximum(period_display[mask_pos], 1))\n"
    "\n"
    "extent = [a_range_p[0], a_range_p[-1], alpha_range_p[0], alpha_range_p[-1]]\n"
    "im = ax.imshow(period_display, extent=extent, aspect='auto', origin='lower',\n"
    "               cmap='viridis', vmin=0, vmax=8)\n"
    "plt.colorbar(im, ax=ax, label='log2(period) [0 = chaotic/diverged]')\n"
    "\n"
    "ax.axhline(1.0, color='white', linestyle='--', linewidth=1, label='alpha=1')\n"
    "ax.axhline(-1.0, color='white', linestyle=':', linewidth=1, label='alpha=-1')\n"
    "ax.axhline(0.0, color='yellow', linestyle='-.', linewidth=1, label='alpha=0')\n"
    "\n"
    "ax.set(xlabel='Parameter a', ylabel='alpha', title='(alpha, a) Period Diagram')\n"
    "ax.legend(loc='upper left')\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

with open('lyapunov_alpha_relationship.ipynb', 'w') as f:
    json.dump(nb, f, indent=1)
print("Updated lyapunov_alpha_relationship.ipynb")

# ============================================================
# 2. RP RESONANCE NOTEBOOK
# ============================================================

with open('rp_resonance_basis.ipynb') as f:
    nb2 = json.load(f)

cells2 = nb2['cells']
code_cells2 = [(i, c) for i, c in enumerate(cells2) if c['cell_type'] == 'code']

# Cell 0 (imports)
code_cells2[0][1]['source'] = to_lines(
    "import sys\n"
    "sys.path.insert(0, '..')\n"
    "\n"
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "from scipy.special import eval_chebyt, eval_chebyu, eval_jacobi\n"
    "from scipy import integrate\n"
    "from petrification.maps import logistic\n"
    "from petrification.quantum import frobenius_perron_matrix, exact_ulam_matrix\n"
    "\n"
    "plt.rcParams.update({'figure.figsize': (12, 5), 'font.size': 12})\n"
    "\n"
    "# Load precomputed results\n"
    "_ulam = np.load('cache/ulam_baseline.npz')\n"
    "_cheb = np.load('cache/cheb_transfer.npz')\n"
    "_other = np.load('cache/rp_other_params.npz')\n"
    "_jacobi = np.load('cache/jacobi_comparison.npz', allow_pickle=True)\n"
    "_conv = np.load('cache/convergence_rate.npz')"
)

# Cell 1 (function defs — keep for reference)
# No changes needed

# Cell 2 (Ulam baseline)
code_cells2[2][1]['source'] = to_lines(
    "# Load precomputed Ulam eigenvalues\n"
    "N_ulam_values = _ulam['N_values']\n"
    "ulam_eigenvalues_arr = _ulam['eigenvalues']\n"
    "n_keep = 6\n"
    "\n"
    "print('Ulam method -- top eigenvalues by resolution:')\n"
    "print(f\"{'N':>6s}\", end='')\n"
    "for k in range(n_keep):\n"
    "    print(f'  |l_{k}|    ', end='')\n"
    "print()\n"
    "\n"
    "ulam_eigenvalues = {}\n"
    "for i, N in enumerate(N_ulam_values):\n"
    "    eigs = ulam_eigenvalues_arr[i]\n"
    "    ulam_eigenvalues[N] = eigs\n"
    "    print(f'{N:6d}', end='')\n"
    "    for k in range(n_keep):\n"
    "        print(f'  {eigs[k]:.6f}', end='')\n"
    "    print()\n"
    "\n"
    "print(f'\\nExact: |l_0| = 1.000000, |l_1| = 0.500000, |l_2| = 0.250000, ...')"
)

# Cell 3 (Chebyshev)
code_cells2[3][1]['source'] = to_lines(
    "# Load precomputed Chebyshev eigenvalues\n"
    "N_cheb_values = _cheb['N_values']\n"
    "cheb_eigenvalues_arr = _cheb['eigenvalues']\n"
    "n_keep = 6\n"
    "\n"
    "print('Weighted Chebyshev -- top eigenvalues by order:')\n"
    "print(f\"{'N':>6s}\", end='')\n"
    "for k in range(n_keep):\n"
    "    print(f'  |l_{k}|    ', end='')\n"
    "print()\n"
    "\n"
    "cheb_eigenvalues = {}\n"
    "for i, N in enumerate(N_cheb_values):\n"
    "    eigs = cheb_eigenvalues_arr[i]\n"
    "    cheb_eigenvalues[N] = eigs\n"
    "    print(f'{N:6d}', end='')\n"
    "    for k in range(n_keep):\n"
    "        print(f'  {eigs[k]:.6f}', end='')\n"
    "    print()\n"
    "\n"
    "print(f'\\nExact: |l_0| = 1.000000, |l_1| = 0.500000, |l_2| = 0.250000, ...')"
)

# Cell 4 (convergence comparison plot) — uses ulam_eigenvalues/cheb_eigenvalues dicts built above
# Keep as-is

# Cell 5 (other params)
code_cells2[5][1]['source'] = to_lines(
    "# Load precomputed RP resonances at other parameter values\n"
    "a_values_test = _other['a_values']\n"
    "ulam_eigs_other = _other['ulam_eigs']\n"
    "cheb_eigs_other = _other['cheb_eigs']\n"
    "N_cheb_test, N_ulam_test = 48, 800\n"
    "\n"
    "fig, axes = plt.subplots(2, 2, figsize=(12, 10))\n"
    "\n"
    "for idx, a_val in enumerate(a_values_test):\n"
    "    ax = axes[idx // 2][idx % 2]\n"
    "    eigs_u = ulam_eigs_other[idx]\n"
    "    eigs_c = cheb_eigs_other[idx]\n"
    "\n"
    "    k_range = np.arange(10)\n"
    "    width = 0.35\n"
    "    ax.bar(k_range - width/2, eigs_u[:10], width, color='red', alpha=0.7, label=f'Ulam (N={N_ulam_test})')\n"
    "    ax.bar(k_range + width/2, eigs_c[:10], width, color='blue', alpha=0.7, label=f'Cheb (N={N_cheb_test})')\n"
    "\n"
    "    if a_val == 4.0:\n"
    "        ax.plot(k_range, [2**(-k) for k in k_range], 'k*', markersize=10, label='Exact')\n"
    "\n"
    "    ax.set(xlabel='Eigenvalue index n', ylabel='|l_n|', title=f'a = {a_val}')\n"
    "    ax.legend(fontsize=8)\n"
    "    ax.set_xticks(k_range)\n"
    "\n"
    "plt.suptitle('RP Spectrum: Ulam vs Weighted Chebyshev', fontsize=13)\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

# Cell 6 (Jacobi comparison)
code_cells2[6][1]['source'] = to_lines(
    "# Load precomputed Jacobi basis comparison\n"
    "basis_names = list(_jacobi['basis_names'])\n"
    "basis_eigs_arr = _jacobi['eigenvalues']\n"
    "\n"
    "N_test = 48\n"
    "print('Basis comparison at a=4, N=48:')\n"
    "print(f\"{'Basis':<25s} |l_0|     |l_1|     |l_2|     |l_3|\")\n"
    "\n"
    "basis_results = {}\n"
    "for i, name in enumerate(basis_names):\n"
    "    eigs = basis_eigs_arr[i]\n"
    "    basis_results[name] = eigs\n"
    "    print(f'{name:<25s} {eigs[0]:.6f} {eigs[1]:.6f} {eigs[2]:.6f} {eigs[3]:.6f}')\n"
    "\n"
    "print(f\"{'EXACT':<25s} 1.000000 0.500000 0.250000 0.125000\")\n"
    "\n"
    "# Error plot\n"
    "fig, ax = plt.subplots(figsize=(10, 6))\n"
    "x_pos = np.arange(4)\n"
    "width = 0.15\n"
    "\n"
    "for i, (name, eigs) in enumerate(basis_results.items()):\n"
    "    errors = [abs(eigs[k] - 2**(-k)) for k in range(4)]\n"
    "    ax.bar(x_pos + i * width, errors, width, label=name, alpha=0.8)\n"
    "\n"
    "ax.set_xticks(x_pos + width * 2)\n"
    "ax.set_xticklabels([f'|l_{k}|' for k in range(4)])\n"
    "ax.set_ylabel('Absolute error')\n"
    "ax.set_title('Basis Comparison: Error in RP Eigenvalues (a=4, N=48)')\n"
    "ax.legend(fontsize=8)\n"
    "ax.set_yscale('log')\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

# Cell 7 (convergence rate)
code_cells2[7][1]['source'] = to_lines(
    "# Load precomputed convergence rate data\n"
    "N_conv = list(_conv['N_values'])\n"
    "conv_eigs = _conv['eigenvalues']\n"
    "\n"
    "best_name = 'Chebyshev T (arcsine)'\n"
    "errors_by_N = {k: [] for k in range(4)}\n"
    "\n"
    "print(f'Convergence study for {best_name} basis:')\n"
    "for i, N in enumerate(N_conv):\n"
    "    eigs = conv_eigs[i]\n"
    "    for k in range(4):\n"
    "        errors_by_N[k].append(abs(eigs[k] - 2**(-k)))\n"
    "    print(f'  N={N:3d}: |l_1| err = {errors_by_N[1][-1]:.2e}, |l_2| err = {errors_by_N[2][-1]:.2e}')\n"
    "\n"
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))\n"
    "\n"
    "# Log-log (algebraic convergence)\n"
    "for k in range(1, 4):\n"
    "    ax1.loglog(N_conv, errors_by_N[k], 'o-', markersize=5, label=f'|l_{k}| error')\n"
    "\n"
    "N_ref = np.array([8, 100])\n"
    "ax1.loglog(N_ref, 0.5 * N_ref**(-2.0), 'k--', alpha=0.3, label='O(1/N^2)')\n"
    "ax1.loglog(N_ref, 0.5 * N_ref**(-4.0), 'k:', alpha=0.3, label='O(1/N^4)')\n"
    "ax1.set(xlabel='N', ylabel='|error|', title='Log-log (algebraic rate?)')\n"
    "ax1.legend(fontsize=8)\n"
    "ax1.grid(True, alpha=0.3)\n"
    "\n"
    "# Semi-log (spectral convergence)\n"
    "for k in range(1, 4):\n"
    "    ax2.semilogy(N_conv, errors_by_N[k], 'o-', markersize=5, label=f'|l_{k}| error')\n"
    "ax2.set(xlabel='N', ylabel='|error|', title='Semi-log (spectral rate?)')\n"
    "ax2.legend(fontsize=8)\n"
    "ax2.grid(True, alpha=0.3)\n"
    "\n"
    "plt.suptitle(f'Convergence Rate: {best_name}', fontsize=13)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "\n"
    "# Fit convergence rate\n"
    "log_N = np.log(np.array(N_conv, dtype=float))\n"
    "log_err = np.log(np.maximum(np.array(errors_by_N[1]), 1e-16))\n"
    "mask = np.isfinite(log_err) & (log_err > -30)\n"
    "if np.sum(mask) >= 3:\n"
    "    slope, _ = np.polyfit(log_N[mask], log_err[mask], 1)\n"
    "    print(f'\\nConvergence rate for |l_1|: O(N^{slope:.2f})')\n"
    "else:\n"
    "    print('\\nInsufficient data for rate fit')"
)

with open('rp_resonance_basis.ipynb', 'w') as f:
    json.dump(nb2, f, indent=1)
print("Updated rp_resonance_basis.ipynb")

# ============================================================
# 3. PIECEWISE DYSON NOTEBOOK
# ============================================================

with open('piecewise_alpha_dyson.ipynb') as f:
    nb3 = json.load(f)

cells3 = nb3['cells']
code_cells3 = [(i, c) for i, c in enumerate(cells3) if c['cell_type'] == 'code']

# Cell 0 (imports)
code_cells3[0][1]['source'] = to_lines(
    "import sys\n"
    "sys.path.insert(0, '..')\n"
    "\n"
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "from petrification.dyson import (\n"
    "    scalar_dyson_iterate, scalar_dyson_exact, scalar_dyson_stability,\n"
    "    spectral_dyson_scan, quadratic_self_energy, cubic_self_energy\n"
    ")\n"
    "\n"
    "plt.rcParams.update({'figure.figsize': (12, 5), 'font.size': 12})\n"
    "eta = 0.05\n"
    "eps0 = 0.0\n"
    "\n"
    "# Load precomputed results\n"
    "_stab_quad = np.load('cache/stability_quadratic.npz')\n"
    "_stab_cubic = np.load('cache/stability_cubic.npz')\n"
    "_stab_multi = np.load('cache/stability_multipole.npz')\n"
    "_pw_quad = np.load('cache/piecewise_quadratic.npz')\n"
    "_pw_cubic = np.load('cache/piecewise_cubic.npz')\n"
    "_pw_multi = np.load('cache/piecewise_multipole.npz')"
)

# Cell 1 (§2: stability landscape)
code_cells3[1][1]['source'] = to_lines(
    "# Load precomputed stability landscapes\n"
    "omega_real = _stab_quad['omega']\n"
    "\n"
    "stability_quad = _stab_quad['stability']\n"
    "alpha_opt_quad = _stab_quad['alpha_opt']\n"
    "stability_cubic = _stab_cubic['stability']\n"
    "alpha_opt_cubic = _stab_cubic['alpha_opt']\n"
    "stability_multi = _stab_multi['stability']\n"
    "alpha_opt_multi = _stab_multi['alpha_opt']\n"
    "\n"
    "# Plot\n"
    "fig, axes = plt.subplots(2, 1, figsize=(14, 8))\n"
    "\n"
    "axes[0].plot(omega_real, stability_quad, 'b-', linewidth=1.5, label='Quadratic: S = U^2 G')\n"
    "axes[0].plot(omega_real, stability_cubic, 'r-', linewidth=1.5, label='Cubic: S = U^2 G + V G^2')\n"
    "axes[0].plot(omega_real, stability_multi, 'g-', linewidth=1.5, label='Multi-pole: S = U^2 G/(1-V^2 G^2)')\n"
    "axes[0].axhline(1, color='k', linestyle='--', alpha=0.5, label='|dF/dG| = 1 (instability)')\n"
    "axes[0].set(ylabel='|dF/dG(G*)|', title='Stability Multiplier vs Frequency')\n"
    "axes[0].legend()\n"
    "axes[0].set_ylim(0, 3)\n"
    "\n"
    "axes[1].plot(omega_real, alpha_opt_quad, 'b-', linewidth=1.5, label='Quadratic')\n"
    "axes[1].plot(omega_real, np.clip(alpha_opt_cubic, 0, 1), 'r-', linewidth=1.5, label='Cubic')\n"
    "axes[1].plot(omega_real, np.clip(alpha_opt_multi, 0, 1), 'g-', linewidth=1.5, label='Multi-pole')\n"
    "axes[1].axhline(0.5, color='gray', linestyle='--', alpha=0.5)\n"
    "axes[1].set(xlabel='omega', ylabel='Optimal alpha*(omega)', title='Optimal Relaxation vs Frequency')\n"
    "axes[1].legend()\n"
    "axes[1].set_ylim(0, 1)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "\n"
    "# Quantify variation\n"
    "print(f'alpha* range (quadratic):  [{alpha_opt_quad.min():.3f}, {alpha_opt_quad.max():.3f}]')\n"
    "print(f'alpha* range (cubic):      [{np.clip(alpha_opt_cubic, 0, 1).min():.3f}, {np.clip(alpha_opt_cubic, 0, 1).max():.3f}]')\n"
    "print(f'alpha* range (multi-pole): [{np.clip(alpha_opt_multi, 0, 1).min():.3f}, {np.clip(alpha_opt_multi, 0, 1).max():.3f}]')"
)

# Cell 2 (§3: piecewise quadratic — control)
code_cells3[2][1]['source'] = to_lines(
    "# Piecewise alpha helper\n"
    "def make_piecewise_alpha(boundaries, alpha_values):\n"
    "    def alpha_func(omega, G, iteration):\n"
    "        w = omega.real if hasattr(omega, 'real') else omega\n"
    "        for i, b in enumerate(boundaries):\n"
    "            if w < b:\n"
    "                return alpha_values[i]\n"
    "        return alpha_values[-1]\n"
    "    return alpha_func\n"
    "\n"
    "# Quadratic self-energy -- control experiment\n"
    "U = 3.0\n"
    "sigma_quad = quadratic_self_energy(U)\n"
    "omega_grid_test = np.linspace(-5, 5, 200) + 1j * eta\n"
    "\n"
    "# Strategy 1: Global alpha = 0.5\n"
    "G_global, n_conv_global, iters_global = spectral_dyson_scan(\n"
    "    omega_grid_test, eps0, sigma_quad, alpha=0.5, n_iter=300, tol=1e-12\n"
    ")\n"
    "\n"
    "# Strategy 2: 3-window piecewise\n"
    "alpha_3win = make_piecewise_alpha([-3, -1, 1, 3], [0.6, 0.5, 0.4, 0.5, 0.6])\n"
    "G_3win, n_conv_3win, iters_3win = spectral_dyson_scan(\n"
    "    omega_grid_test, eps0, sigma_quad, alpha=alpha_3win, n_iter=300, tol=1e-12\n"
    ")\n"
    "\n"
    "# Strategy 3: Oracle piecewise -- use precomputed alpha*(omega)\n"
    "alpha_oracle_interp = np.interp(omega_grid_test.real, _stab_quad['omega'], _stab_quad['alpha_opt'])\n"
    "\n"
    "G_oracle_list = []\n"
    "iters_oracle = []\n"
    "for j, omega in enumerate(omega_grid_test):\n"
    "    G0 = 1.0 / (omega - eps0)\n"
    "    a_val = float(np.clip(alpha_oracle_interp[j], 0.1, 0.9))\n"
    "    hist, conv = scalar_dyson_iterate(omega, eps0, sigma_quad, G0, alpha=a_val, n_iter=300, tol=1e-12)\n"
    "    G_oracle_list.append(hist[-1])\n"
    "    iters_oracle.append(len(hist) - 1 if conv else 300)\n"
    "iters_oracle = np.array(iters_oracle)\n"
    "\n"
    "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 7))\n"
    "\n"
    "A_global = -1/np.pi * np.imag(G_global)\n"
    "A_3win = -1/np.pi * np.imag(G_3win)\n"
    "A_oracle = -1/np.pi * np.imag(np.array(G_oracle_list))\n"
    "\n"
    "ax1.plot(omega_grid_test.real, A_global, 'b-', linewidth=2, label='Global alpha=0.5')\n"
    "ax1.plot(omega_grid_test.real, A_3win, 'r--', linewidth=2, label='3-window piecewise')\n"
    "ax1.plot(omega_grid_test.real, A_oracle, 'g:', linewidth=2, label='Oracle alpha*(omega)')\n"
    "ax1.set(ylabel='A(omega)', title='Spectral Function: Quadratic Sigma (Control)')\n"
    "ax1.legend()\n"
    "\n"
    "ax2.plot(omega_grid_test.real, iters_global, 'b-', linewidth=1.5, label='Global alpha=0.5')\n"
    "ax2.plot(omega_grid_test.real, iters_3win, 'r--', linewidth=1.5, label='3-window')\n"
    "ax2.plot(omega_grid_test.real, iters_oracle, 'g:', linewidth=1.5, label='Oracle alpha*(omega)')\n"
    "ax2.set(xlabel='omega', ylabel='Iterations', title='Convergence Speed')\n"
    "ax2.legend()\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "\n"
    "print(f'Global alpha=0.5:  {n_conv_global}/{len(omega_grid_test)} converged, avg {np.mean(iters_global):.1f} iters')\n"
    "print(f'3-window:          {n_conv_3win}/{len(omega_grid_test)} converged, avg {np.mean(iters_3win):.1f} iters')\n"
    "n_conv_oracle = sum(1 for i in iters_oracle if i < 300)\n"
    "print(f'Oracle alpha*(w):  {n_conv_oracle}/{len(omega_grid_test)} converged, avg {np.mean(iters_oracle):.1f} iters')"
)

# Cell 3 (§4: cubic piecewise) — use cached window alphas
code_cells3[3][1]['source'] = to_lines(
    "# Cubic self-energy: Sigma = U^2 G + V G^2\n"
    "U, V = 3.0, 1.5\n"
    "sigma_cub = cubic_self_energy(U, V)\n"
    "omega_grid_test = np.linspace(-5, 5, 200) + 1j * eta\n"
    "\n"
    "# Constant alpha scan\n"
    "conv_landscape = {}\n"
    "for alpha_val in [0.3, 0.4, 0.5, 0.6, 0.7]:\n"
    "    G_arr, n_conv, iters = spectral_dyson_scan(\n"
    "        omega_grid_test, eps0, sigma_cub, alpha=alpha_val, n_iter=500, tol=1e-12\n"
    "    )\n"
    "    conv_landscape[alpha_val] = (G_arr, n_conv, iters)\n"
    "    print(f'alpha = {alpha_val}: {n_conv}/{len(omega_grid_test)} converged, avg iter = {np.mean(iters):.1f}')\n"
    "\n"
    "best_const_alpha = max(conv_landscape, key=lambda a: conv_landscape[a][1])\n"
    "print(f'\\nBest constant alpha = {best_const_alpha}')\n"
    "\n"
    "# Load precomputed piecewise window alphas\n"
    "windows = [(-5, -2), (-2, -0.5), (-0.5, 0.5), (0.5, 2), (2, 5)]\n"
    "window_alphas = list(_pw_cubic['window_alphas'])\n"
    "for (wlo, whi), wa in zip(windows, window_alphas):\n"
    "    print(f'Window [{wlo:+.1f}, {whi:+.1f}): optimal alpha = {wa:.3f}')\n"
    "\n"
    "# Run piecewise\n"
    "boundaries = [w[1] for w in windows[:-1]]\n"
    "alpha_pw_opt = make_piecewise_alpha(boundaries, window_alphas)\n"
    "G_pw, n_conv_pw, iters_pw = spectral_dyson_scan(\n"
    "    omega_grid_test, eps0, sigma_cub, alpha=alpha_pw_opt, n_iter=500, tol=1e-12\n"
    ")\n"
    "\n"
    "G_const, n_conv_const, iters_const = conv_landscape[best_const_alpha]\n"
    "\n"
    "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 7))\n"
    "\n"
    "A_const = -1/np.pi * np.imag(G_const)\n"
    "A_pw = -1/np.pi * np.imag(G_pw)\n"
    "\n"
    "ax1.plot(omega_grid_test.real, A_const, 'b-', linewidth=2, label=f'Constant alpha={best_const_alpha}')\n"
    "ax1.plot(omega_grid_test.real, A_pw, 'r--', linewidth=2, label='Piecewise optimized')\n"
    "ax1.set(ylabel='A(omega)', title=f'Cubic Sigma: U={U}, V={V}')\n"
    "ax1.legend()\n"
    "\n"
    "ax2.plot(omega_grid_test.real, iters_const, 'b-', linewidth=1.5, label=f'Constant alpha={best_const_alpha}')\n"
    "ax2.plot(omega_grid_test.real, iters_pw, 'r-', linewidth=1.5, label='Piecewise')\n"
    "ax2.set(xlabel='omega', ylabel='Iterations', title='Convergence Speed')\n"
    "ax2.legend()\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "\n"
    "print(f'\\nConstant alpha={best_const_alpha}: {n_conv_const}/{len(omega_grid_test)} conv, avg {np.mean(iters_const):.1f}')\n"
    "print(f'Piecewise optimized: {n_conv_pw}/{len(omega_grid_test)} conv, avg {np.mean(iters_pw):.1f}')"
)

# Cell 4 (§5: multipole) — use cached window alphas
code_cells3[4][1]['source'] = to_lines(
    "# Multi-pole self-energy\n"
    "U_mp, V_pole = 2.5, 0.8\n"
    "\n"
    "def multipole_self_energy(U, V):\n"
    "    def sigma(G):\n"
    "        denom = 1 - V**2 * G**2\n"
    "        if abs(denom) < 1e-20:\n"
    "            return U**2 * G\n"
    "        return U**2 * G / denom\n"
    "    return sigma\n"
    "\n"
    "sigma_mp = multipole_self_energy(U_mp, V_pole)\n"
    "\n"
    "# Constant alpha scan\n"
    "print('Constant alpha scan (multi-pole self-energy):')\n"
    "best_const_a, best_conv = 0.5, 0\n"
    "conv_landscape_mp = {}\n"
    "for alpha_val in np.linspace(0.1, 0.9, 17):\n"
    "    G_arr, n_conv, iters = spectral_dyson_scan(\n"
    "        omega_grid_test, eps0, sigma_mp, alpha=alpha_val, n_iter=500, tol=1e-12\n"
    "    )\n"
    "    conv_landscape_mp[alpha_val] = (G_arr, n_conv, iters)\n"
    "    if n_conv > best_conv or (n_conv == best_conv and np.mean(iters) < 500):\n"
    "        best_const_a, best_conv = alpha_val, n_conv\n"
    "    print(f'  alpha = {alpha_val:.2f}: {n_conv}/{len(omega_grid_test)} converged, avg iter = {np.mean(iters):.1f}')\n"
    "\n"
    "print(f'\\nBest constant: alpha = {best_const_a}')\n"
    "\n"
    "# Load precomputed piecewise window alphas\n"
    "windows_mp = [(-5, -2), (-2, -0.5), (-0.5, 0.5), (0.5, 2), (2, 5)]\n"
    "window_alphas_mp = list(_pw_multi['window_alphas'])\n"
    "for (wlo, whi), wa in zip(windows_mp, window_alphas_mp):\n"
    "    print(f'Window [{wlo:+.1f}, {whi:+.1f}): optimal alpha = {wa:.3f}')\n"
    "\n"
    "# Run piecewise\n"
    "boundaries_mp = [w[1] for w in windows_mp[:-1]]\n"
    "alpha_pw_mp = make_piecewise_alpha(boundaries_mp, window_alphas_mp)\n"
    "G_pw_mp, n_conv_pw_mp, iters_pw_mp = spectral_dyson_scan(\n"
    "    omega_grid_test, eps0, sigma_mp, alpha=alpha_pw_mp, n_iter=500, tol=1e-12\n"
    ")\n"
    "\n"
    "G_const_mp, n_conv_const_mp, iters_const_mp = conv_landscape_mp[best_const_a]\n"
    "\n"
    "fig, axes = plt.subplots(3, 1, figsize=(14, 10))\n"
    "\n"
    "# Stability landscape\n"
    "axes[0].plot(omega_grid_test.real,\n"
    "             np.interp(omega_grid_test.real, _stab_multi['omega'], _stab_multi['stability']),\n"
    "             'k-', linewidth=1.5)\n"
    "axes[0].axhline(1, color='r', linestyle='--', alpha=0.5)\n"
    "axes[0].set(ylabel='|dF/dG(G*)|', title='Stability Landscape (Multi-pole Sigma)')\n"
    "for i, (wlo, whi) in enumerate(windows_mp):\n"
    "    axes[0].axvspan(wlo, whi, alpha=0.1, color=f'C{i}')\n"
    "    axes[0].text((wlo+whi)/2, 2.5, f'a={window_alphas_mp[i]:.2f}', ha='center', fontsize=9)\n"
    "axes[0].set_ylim(0, 3)\n"
    "\n"
    "# Spectral functions\n"
    "A_const_mp = -1/np.pi * np.imag(G_const_mp)\n"
    "A_pw_mp_plot = -1/np.pi * np.imag(G_pw_mp)\n"
    "axes[1].plot(omega_grid_test.real, A_const_mp, 'b-', linewidth=2, label=f'Constant alpha={best_const_a:.2f}')\n"
    "axes[1].plot(omega_grid_test.real, A_pw_mp_plot, 'r--', linewidth=2, label='Piecewise')\n"
    "axes[1].set(ylabel='A(omega)', title='Spectral Function')\n"
    "axes[1].legend()\n"
    "\n"
    "# Iteration counts\n"
    "axes[2].plot(omega_grid_test.real, iters_const_mp, 'b-', linewidth=1.5, label='Constant')\n"
    "axes[2].plot(omega_grid_test.real, iters_pw_mp, 'r-', linewidth=1.5, label='Piecewise')\n"
    "axes[2].set(xlabel='omega', ylabel='Iterations', title='Convergence Speed')\n"
    "axes[2].legend()\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "\n"
    "print(f'\\n{\"=\"*60}')\n"
    "print(f'Constant alpha={best_const_a:.2f}: {n_conv_const_mp}/{len(omega_grid_test)} converged, avg {np.mean(iters_const_mp):.1f} iters')\n"
    "print(f'Piecewise:     {n_conv_pw_mp}/{len(omega_grid_test)} converged, avg {np.mean(iters_pw_mp):.1f} iters')\n"
    "improvement = np.mean(iters_const_mp) - np.mean(iters_pw_mp)\n"
    "print(f'Piecewise saves {improvement:.1f} iters/freq on average')"
)

# Cell 5 (§6: window count sweep) — leave as-is, it's relatively fast

with open('piecewise_alpha_dyson.ipynb', 'w') as f:
    json.dump(nb3, f, indent=1)
print("Updated piecewise_alpha_dyson.ipynb")

print("\nAll 3 notebooks updated to use cached results.")
